name: drone-test1
kind: pipeline
type: docker
steps:
  - name: build
    image: ubuntu:18.04
    privileged: true
    commands:
      - apt update -y
      - apt upgrade -y
      - touch memo.md
      - pwd
      - ls -al
      - echo "hello world" >> ./memo.md

  - name: build_part2
    image: ubuntu:20.04
    privileged: true
    commands:
      - apt update -y
      - apt upgrade -y
      - pwd
      - ls -al

  - name: notify
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
    template: >
        {{#success build.status}}
          Deploy Blog of build-{{build.number}} succeeded. Good job. <@huluohu> <@iam>
        {{else}}
          Deploy Blog of build-{{build.number}} failed. Fix me please. <@huluohu> <@iam>
        {{/success}}
    when:
      status: [ success, failure ]
