name: drone-test1
kind: pipeline
type: docker
steps:
  - name: build
    image: ubuntu:18.04
    privileged: true
    commands:
      - apt update -y
      - apt upgrade -y
      - touch memo.md
      - pwd
      - ls -al
      - echo "hello world" >> ./memo.md

  - name: build_part2
    image: ubuntu:20.04
    privileged: true
    commands:
      - apt update -y
      - apt upgrade -y
      - pwd
      - ls -al

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      icon_emoji: ':drone-cicd:'
      template: >
        {{#success build.status}} ✔ {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}      
    when:
      status: [ success, failure ]
