name: drone-test1
kind: pipeline
type: docker
steps:
  - name: build
    image: ubuntu:18.04
    privileged: true
    commands:
      - apt update -y
      - apt upgrade -y
      - touch memo.md
      - pwd
      - ls -al
      - echo "hello world" >> ./memo.md

  - name: build_part2
    image: ubuntu:20.04
    privileged: true
    commands:
      - apt update -y
      - apt upgrade -y
      - pwd
      - ls -al

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
