name: drone-test1
kind: pipeline
type: docker
steps:
  - name: build
    image: ubuntu:18.04
    privileged: true
    commands:
      - apt update -y
      - touch memo.md
      - cat "hello world" >> ./memo.md